package org.apache.cayenne.tutorial.ws.model.auto;

import java.util.List;

import org.apache.cayenne.tutorial.ws.model.Other;
import org.apache.cayenne.tutorial.ws.model.RestDataObject;

/**
 * Class _Thing was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Thing extends RestDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String OTHERS_PROPERTY = "others";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToOthers(Other obj) {
        addToManyTarget("others", obj, true);
    }
    public void removeFromOthers(Other obj) {
        removeToManyTarget("others", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Other> getOthers() {
        return (List<Other>)readProperty("others");
    }


}
